import sys
from setuptools import setup

assert sys.version_info >= (3, 6, 0)

setup(
    name="utilities-package",
    version="0.0.7",
    description="utilities package",
    url="https://github.com/terminal-labs/utilities-package",
    author="Terminal Labs",
    author_email="solutions@terminallabs.com",
    license="see LICENSE file",
    packages=["utilities", "utilities.standard"],
    zip_safe=False,
    install_requires=[
        "setuptools",
        "six",
        "bash",
        "configparser",
        "unidecode",
        "uritools",
        "simplejson",
        "tailer",
        "pytz",
        "termcolor",
        "texttable",
        "schedule",
        "python-dateutil",
        "beautifulsoup4",
        "cssutils",
        "base58",
        "bcrypt",
        "aiohttp",
        "requests",
        "tornado",
        "cherrypy",
        "bottle",
        "flask",
        "click",
        "Jinja2",
        "coverage",
        "pycontracts",
        "pytest",
        "pytest-cov",
        "pytest-mock",
        "pytest-click",
        "pytest-pylint",
        "black",
        "flake8",
        "radon",
        "cli-passthrough",
    ],
)
