version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Mock vagrant
          command: |
            sudo bash .circleci/mock_vagrant.sh
      - run:
          name: Install deps
          command: |
            cd /vagrant; sudo bash maintenance/install_deps.sh
      - run:
          name: Install python
          command: |
            cd /vagrant; sudo bash maintenance/install_python.sh
      - run:
          name: Install app
          command: |
            cd /vagrant; sudo bash maintenance/install_app.sh
      - run:
          name: Run tests
          command: |
            cd /vagrant; sudo bash maintenance/run_tests.sh
