version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Root Setup
          command: |
            bash scripts/root-setup.sh

      - run:
          name: Non Root Setup
          command: |
            bash scripts/non-root-setup.sh
